### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by dharshini78**

### CODE REVIEW

**Comment by Kavya-24** [comment]
Hi @dharshini78 . Great gesture for adding images on the README.md. However, the first image that you have added is the intellectual property of the AUTO-DL. Kindly refrain from using that :) 
The second image is fine :)

**Comment by dharshini78** [comment]
> Hi @dharshini78 . Great gesture for adding images on the README.md. However, the first image that you have added is the intellectual property of the AUTO-DL. Kindly refrain from using that :) The second image is fine :)

hey @Kavya-24 I had made the necessary changes! hope you like it..

**Comment by Kavya-24** [comment]
Hi @dharshini78 , could you please resolve the merge conflict and get back to me :)

**Comment by Kavya-24** [comment]
Hi @dharshini78 , your branch `patch-2` (Which you have used for this PR for example) is a lot of commits behind. There have been new changes in the README.md, and also files like CONTRIBUTING.md have been added. You will need to pull files from upstream and update your branches. Then your changes wont be conflicting :)
Tell me if you face any difficulty. Would love to help. ❤

**Comment by Kavya-24** [comment]
You can go ahead and create a new pull request for your next changes. Closing this PR :)

**Comment by dharshini78** [comment]
> Hi @dharshini78 , your branch `patch-2` (Which you have used for this PR for example) is a lot of commits behind. There have been new changes in the README.md, and also files like CONTRIBUTING.md have been added. You will need to pull files from upstream and update your branches. Then your changes wont be conflicting :)
> Tell me if you face any difficulty. Would love to help. ❤
> 

Yes , I am a beginner actually, I am facing some difficulties. Could you tell me what should I do now !

**Pull request closed without merging**
