### PR TITLE
tic tac game

### PR DESCRIPTION
**Pull request by Swapnil05Rai**
python game

### CODE REVIEW

**Comment by Kavya-24** [comment]
@Swapnil05Rai , Welcome to the repository
Could you add the `tictac` program you have created in an appropriate folder like the `python` or `projects` folder
Do tell if you need any help. Happy coding :)

**Review by Kavya-24 — CHANGES_REQUESTED** [review]
Could you add the `tictac` program you have created in an appropriate folder like the `python` or `projects` folder

**Comment by Swapnil05Rai** [comment]
Done, please accept the changes.

**Review by Kavya-24 — APPROVED** [review]

**Comment by Kavya-24** [comment]
Great work @Swapnil05Rai

**Pull request merged**
